name: Upload Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy site to gh-pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Load dependancies
        run: yarn

      - name: Deploy to gh-pages branch
        run: yarn deploy
